import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./commponent/nav.js";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kishan Electronic store",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon-32x32.png?v=4"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
